[default]
server_host = "0.0.0.0"
server_port = 8000

[default.db]
host = "db"
port = 5432
name = "moods_dev"
user = "moods_dev"
password = "moods_dev"

[development]

[testing]
dynaconf_merge = true

[testing.db]
name = "moods_test"
